# Project: dbutils
# 
# Author: Renaud Gaujoux
# Created: Nov 18, 2013
###############################################################################


#' Check Connection Validity
#' 
#' \code{dbIsValid} tests if a connection is valid, i.e. open.
#' 
#' @param con connection object, as returned by \code{\link{dbConnect}}.
#' @export
#' 
#' 
dbIsValid <- function(con){
    !is( try( dbGetInfo(con), silent = TRUE), 'try-error' )
}

#' \code{dbReset} resets all cached database connections, which were generated by \code{.DBConnector} 
#' @rdname db-internals 
dbReset <- function(){
	
	.reset <- function(f){
		if( !is(try(f()), 'try-error') ){
			dbDisconnect(f())
		}
		forget(f)
	}
	# disconnect
	con <- lapply(dbListConnections(MySQL()), dbDisconnect)
	.reset(dbGEO)
	.reset(dbNOSOLOGY)
	
	# return number of disonnected connections 
	length(con)
}


dbCommit <- function(con){
    rs <- dbSendQuery(con, 'COMMIT;')
    dbClearResult(rs)
}

dbRollback <- function(con){
    rs <- dbSendQuery(con, 'ROLLBACK;')
    dbClearResult(rs)
}

dbStartTransaction <- function(con){
    rs <- dbSendQuery(con, 'START TRANSACTION;')
    dbClearResult(rs)
}

